name: Test directory script

on:
  schedule:
    - cron: '45 11,23 * * *'

jobs:
  directory:
    name: python
    runs-on: ubuntu-latest
    env:
      praw_refresh_token:  ${{secrets.PRAW_REFRESH_TOKEN}}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run directory test
        run: uv run rcounting update-directory -v --sleep 5 --no-allow-archive
